# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(max_length=300)),
                ('option4', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('receipt_number', models.IntegerField(max_length=5)),
                ('phone_number1', models.IntegerField(max_length=11)),
                ('phone_number2', models.IntegerField(max_length=11)),
                ('college_name1', models.CharField(max_length=100)),
                ('college_name2', models.CharField(max_length=100)),
                ('user_name1', models.CharField(max_length=100)),
                ('user_name2', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('attempted_questions', models.CharField(max_length=1000)),
                ('attempted_answers', models.CharField(max_length=1000)),
                ('total_score', models.IntegerField(max_length=3)),
                ('rank', models.IntegerField(max_length=3)),
            ],
        ),
    ]
