# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_score',
        ),
    ]
