# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20161214_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTable',
            new_name='Questions',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
