# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_user_question_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='question_array',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
