# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0009_auto_20161218_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
