# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0010_auto_20161218_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correct_answered',
            field=models.IntegerField(default=0),
        ),
    ]
