# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0012_auto_20161219_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_bonus',
            new_name='user_bonus_activated',
        ),
        migrations.AddField(
            model_name='user',
            name='user_bonus_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
