# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0013_auto_20161219_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
    ]
