# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0014_user_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=2000),
        ),
    ]
