# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2002-01-01 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0015_auto_20161230_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
