# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2002-01-01 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0016_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
