# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0017_auto_20020101_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
