# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0018_remove_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
    ]
